# Generated by Django 5.2.5 on 2025-09-01 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='uploaded_file',
            field=models.FileField(upload_to='media/resumes/'),
        ),
    ]
